<a href="https://colab.research.google.com/github/iamshahidkamal/Accio-notes/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

pytorch fundamentals


In [ ]:
import torch
print(torch.__version__)

2.5.1+cu121


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

##Introduction to tensors


##creating tensors

## pytorch tensors are created using torch.Tensors()

In [ ]:
##scalars
scalar = torch.tensor(7)
scalar

tensor(7)

scalars has no dimesions, it just a single number

In [ ]:
scalar.ndim

0

In [ ]:
#get scalar back back as python int
scalar.item()

7

In [ ]:
#vector

vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
##MATRIX
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

it says we have got 1 3 by 3 tensor

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors
nn works with random numbers and then they adjust those random numbersto better represent the data

In [ ]:
# Create a random tensor of shape/size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8017, 0.8366, 0.4272, 0.9792],
        [0.5556, 0.8051, 0.8914, 0.9290],
        [0.6633, 0.3474, 0.1012, 0.2132]])

In [ ]:
random_tensor.ndim

2

In [ ]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)